# Generated by Django 6.0.4 on 2026-04-08 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_phone_number_user_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='roll_no',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
