# Generated by Django 6.0.4 on 2026-04-24 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_platforminquiry_user_email_verified_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='supabase_user_id',
            field=models.CharField(blank=True, max_length=80, null=True, unique=True),
        ),
    ]
