# Generated by Django 6.0.4 on 2026-05-07 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_profile_picture_filefield'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='emailverificationotp',
            index=models.Index(fields=['expires_at', 'is_used'], name='acct_otp_exp_used_idx'),
        ),
        migrations.AddIndex(
            model_name='institution',
            index=models.Index(fields=['verification_status', 'created_at'], name='acct_inst_verify_created_idx'),
        ),
        migrations.AddIndex(
            model_name='platforminquiry',
            index=models.Index(fields=['status', 'created_at'], name='acct_inq_status_created_idx'),
        ),
        migrations.AddIndex(
            model_name='platforminquiry',
            index=models.Index(fields=['verification_status', 'created_at'], name='acct_inq_verify_created_idx'),
        ),
        migrations.AddIndex(
            model_name='platforminquiry',
            index=models.Index(fields=['institution_domain'], name='acct_inquiry_domain_idx'),
        ),
        migrations.AddIndex(
            model_name='platforminquiry',
            index=models.Index(fields=['linked_institution', 'status'], name='acct_inquiry_inst_status_idx'),
        ),
        migrations.AddIndex(
            model_name='platforminquiry',
            index=models.Index(fields=['email'], name='acct_inquiry_email_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['role', 'institution'], name='acct_user_role_inst_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['institution', 'date_joined'], name='acct_user_inst_joined_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='acct_user_email_idx'),
        ),
    ]
