# Generated by Django 6.0.4 on 2026-04-07 22:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(choices=[('1_monday', 'Monday'), ('2_tuesday', 'Tuesday'), ('3_wednesday', 'Wednesday'), ('4_thursday', 'Thursday'), ('5_friday', 'Friday'), ('6_saturday', 'Saturday')], max_length=15)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('room_number', models.CharField(max_length=50)),
                ('course_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='academics.courseclass')),
            ],
            options={
                'ordering': ['day_of_week', 'start_time'],
            },
        ),
    ]
