# Generated by Django 6.0.4 on 2026-04-07 23:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_exam_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='exam_type',
            field=models.CharField(choices=[('mid_sem', 'Mid Sem'), ('end_sem', 'End Sem'), ('quiz', 'Quiz'), ('class_test', 'Class Test'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.CreateModel(
            name='StudyMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='materials/')),
                ('url', models.URLField(blank=True, null=True)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('course_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='academics.courseclass')),
            ],
            options={
                'ordering': ['-upload_date'],
            },
        ),
    ]
