# Generated by Django 6.0.4 on 2026-04-07 23:57

import academics.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0005_exam_exam_type_studymaterial'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseclass',
            name='class_code',
            field=models.CharField(default=academics.models.generate_class_code, max_length=10),
        ),
    ]
