# Generated by Django 6.0.4 on 2026-04-07 23:58

import academics.models
from django.db import migrations, models


def backfill_unique_class_codes(apps, schema_editor):
    CourseClass = apps.get_model('academics', 'CourseClass')
    used_codes = set()

    for course_class in CourseClass.objects.order_by('id'):
        current_code = course_class.class_code
        if current_code and current_code not in used_codes:
            used_codes.add(current_code)
            continue

        base_code = f"CLS{course_class.id:06d}"[-10:]
        candidate = base_code
        suffix = 1
        while candidate in used_codes:
            suffix_text = str(suffix)
            candidate = f"{base_code[:10 - len(suffix_text)]}{suffix_text}"
            suffix += 1

        course_class.class_code = candidate
        course_class.save(update_fields=['class_code'])
        used_codes.add(candidate)


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0006_courseclass_class_code'),
    ]

    operations = [
        migrations.RunPython(backfill_unique_class_codes, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='courseclass',
            name='class_code',
            field=models.CharField(default=academics.models.generate_class_code, max_length=10, unique=True),
        ),
    ]
