# Generated by Django 6.0.4 on 2026-04-23 20:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def seed_departments(apps, schema_editor):
    Department = apps.get_model('academics', 'Department')
    CourseClass = apps.get_model('academics', 'CourseClass')
    User = apps.get_model('accounts', 'User')

    names = set()
    for name in CourseClass.objects.values_list('department', flat=True):
        if name and name.strip():
            names.add(name.strip())
    for name in User.objects.values_list('department', flat=True):
        if name and name.strip():
            names.add(name.strip())

    for name in sorted(names, key=str.lower):
        if not Department.objects.filter(name__iexact=name).exists():
            Department.objects.create(name=name)


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0007_alter_courseclass_class_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, limit_choices_to={'role': 'admin'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_departments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.RunPython(seed_departments, migrations.RunPython.noop),
    ]
