# Generated by Django 6.0.4 on 2026-05-07 13:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0009_institution_scoping'),
        ('accounts', '0007_profile_picture_filefield'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='classschedule',
            index=models.Index(fields=['course_class', 'day_of_week', 'start_time'], name='acad_sched_class_day_idx'),
        ),
        migrations.AddIndex(
            model_name='courseclass',
            index=models.Index(fields=['institution', 'teacher'], name='acad_class_inst_teacher_idx'),
        ),
        migrations.AddIndex(
            model_name='courseclass',
            index=models.Index(fields=['institution', 'department'], name='acad_class_inst_dept_idx'),
        ),
        migrations.AddIndex(
            model_name='courseclass',
            index=models.Index(fields=['teacher', 'subject'], name='acad_class_teacher_subject_idx'),
        ),
        migrations.AddIndex(
            model_name='department',
            index=models.Index(fields=['institution', 'name'], name='acad_dept_inst_name_idx'),
        ),
        migrations.AddIndex(
            model_name='department',
            index=models.Index(fields=['institution', 'is_active'], name='acad_dept_inst_active_idx'),
        ),
        migrations.AddIndex(
            model_name='exam',
            index=models.Index(fields=['course_class', 'date'], name='acad_exam_class_date_idx'),
        ),
        migrations.AddIndex(
            model_name='exam',
            index=models.Index(fields=['date', 'exam_type'], name='acad_exam_date_type_idx'),
        ),
        migrations.AddIndex(
            model_name='grade',
            index=models.Index(fields=['student', 'exam'], name='acad_grade_student_exam_idx'),
        ),
        migrations.AddIndex(
            model_name='studymaterial',
            index=models.Index(fields=['course_class', 'upload_date'], name='acad_material_class_date_idx'),
        ),
    ]
