# Generated by Django 6.0.4 on 2026-04-07 23:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0005_exam_exam_type_studymaterial'),
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='target_class',
            field=models.ForeignKey(blank=True, help_text='Select if this is a classroom notice', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='class_notices', to='academics.courseclass'),
        ),
    ]
