# Generated by Django 6.0.4 on 2026-05-07 13:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0010_classschedule_acad_sched_class_day_idx_and_more'),
        ('dashboard', '0007_media_filefields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['user', 'created_at'], name='dash_activity_user_created_idx'),
        ),
        migrations.AddIndex(
            model_name='bookmark',
            index=models.Index(fields=['user', 'created_at'], name='dash_bookmark_user_date_idx'),
        ),
        migrations.AddIndex(
            model_name='chatsession',
            index=models.Index(fields=['user', 'updated_at'], name='dash_chat_user_updated_idx'),
        ),
        migrations.AddIndex(
            model_name='circular',
            index=models.Index(fields=['department', 'issued_date'], name='dash_circular_dept_date_idx'),
        ),
        migrations.AddIndex(
            model_name='circular',
            index=models.Index(fields=['is_urgent', 'issued_date'], name='dash_circular_urgent_idx'),
        ),
        migrations.AddIndex(
            model_name='circularreceipt',
            index=models.Index(fields=['user', 'read_at'], name='dash_circ_receipt_user_idx'),
        ),
        migrations.AddIndex(
            model_name='classrecording',
            index=models.Index(fields=['course_class', 'recording_date'], name='dash_record_class_date_idx'),
        ),
        migrations.AddIndex(
            model_name='classrecording',
            index=models.Index(fields=['uploaded_by', 'recording_date'], name='dash_record_uploader_date_idx'),
        ),
        migrations.AddIndex(
            model_name='complaint',
            index=models.Index(fields=['status', 'filed_by'], name='dash_complaint_status_file_idx'),
        ),
        migrations.AddIndex(
            model_name='complaint',
            index=models.Index(fields=['assigned_to', 'status'], name='dash_complaint_assignee_idx'),
        ),
        migrations.AddIndex(
            model_name='complaint',
            index=models.Index(fields=['priority', 'status'], name='dash_complaint_priority_idx'),
        ),
        migrations.AddIndex(
            model_name='coursefeedback',
            index=models.Index(fields=['course_class', 'submitted_at'], name='dash_feedback_class_date_idx'),
        ),
        migrations.AddIndex(
            model_name='coursefeedback',
            index=models.Index(fields=['student', 'submitted_at'], name='dash_feedback_student_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['event_date', 'course_class'], name='dash_event_date_class_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['course_class', 'event_date'], name='dash_event_class_date_idx'),
        ),
        migrations.AddIndex(
            model_name='examseat',
            index=models.Index(fields=['room', 'seat_number'], name='dash_examseat_room_idx'),
        ),
        migrations.AddIndex(
            model_name='feerecord',
            index=models.Index(fields=['student', 'status', 'due_date'], name='dash_fee_stu_stat_due_idx'),
        ),
        migrations.AddIndex(
            model_name='feerecord',
            index=models.Index(fields=['status', 'due_date'], name='dash_fee_status_due_idx'),
        ),
        migrations.AddIndex(
            model_name='homeworkentry',
            index=models.Index(fields=['course_class', 'due_date'], name='dash_homework_class_due_idx'),
        ),
        migrations.AddIndex(
            model_name='homeworkentry',
            index=models.Index(fields=['teacher', 'due_date'], name='dash_homework_teacher_due_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryitem',
            index=models.Index(fields=['category', 'condition'], name='dash_inv_cat_cond_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryitem',
            index=models.Index(fields=['location', 'category'], name='dash_inv_loc_cat_idx'),
        ),
        migrations.AddIndex(
            model_name='notice',
            index=models.Index(fields=['target_role', 'created_at'], name='dash_notice_role_created_idx'),
        ),
        migrations.AddIndex(
            model_name='notice',
            index=models.Index(fields=['target_class', 'created_at'], name='dash_notice_class_date_idx'),
        ),
        migrations.AddIndex(
            model_name='notice',
            index=models.Index(fields=['priority', 'created_at'], name='dash_notice_priority_idx'),
        ),
        migrations.AddIndex(
            model_name='photo',
            index=models.Index(fields=['album', 'uploaded_at'], name='dash_photo_album_date_idx'),
        ),
        migrations.AddIndex(
            model_name='photo',
            index=models.Index(fields=['uploaded_by', 'uploaded_at'], name='dash_photo_user_date_idx'),
        ),
        migrations.AddIndex(
            model_name='photoalbum',
            index=models.Index(fields=['created_by', 'date'], name='dash_album_creator_date_idx'),
        ),
        migrations.AddIndex(
            model_name='photoalbum',
            index=models.Index(fields=['event', 'date'], name='dash_album_event_date_idx'),
        ),
        migrations.AddIndex(
            model_name='scholarship',
            index=models.Index(fields=['is_active', 'deadline'], name='dash_scholar_active_dead_idx'),
        ),
        migrations.AddIndex(
            model_name='scholarship',
            index=models.Index(fields=['department', 'deadline'], name='dash_scholar_dept_dead_idx'),
        ),
        migrations.AddIndex(
            model_name='scholarshipapplication',
            index=models.Index(fields=['status', 'applied_date'], name='dash_sch_app_status_date_idx'),
        ),
        migrations.AddIndex(
            model_name='studygroup',
            index=models.Index(fields=['course_class', 'created_at'], name='dash_group_class_created_idx'),
        ),
        migrations.AddIndex(
            model_name='studygroup',
            index=models.Index(fields=['created_by', 'created_at'], name='dash_group_creator_date_idx'),
        ),
        migrations.AddIndex(
            model_name='studygroupmessage',
            index=models.Index(fields=['group', 'timestamp'], name='dash_group_msg_time_idx'),
        ),
        migrations.AddIndex(
            model_name='studygroupmessage',
            index=models.Index(fields=['sender', 'timestamp'], name='dash_group_msg_sender_idx'),
        ),
        migrations.AddIndex(
            model_name='todoitem',
            index=models.Index(fields=['user', 'is_done', 'due_date'], name='dash_todo_user_done_due_idx'),
        ),
        migrations.AddIndex(
            model_name='todoitem',
            index=models.Index(fields=['user', 'priority'], name='dash_todo_user_priority_idx'),
        ),
        migrations.AddIndex(
            model_name='visitorlog',
            index=models.Index(fields=['out_time', 'in_time'], name='dash_visitor_out_in_idx'),
        ),
        migrations.AddIndex(
            model_name='visitorlog',
            index=models.Index(fields=['approved_by', 'in_time'], name='dash_visitor_approver_idx'),
        ),
    ]
