# Generated by Django 4.2.29 on 2026-04-13 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='is_plagiarized',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='submission',
            name='plagiarism_note',
            field=models.TextField(blank=True),
        ),
    ]
