# Generated by Django 6.0.4 on 2026-05-07 13:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0010_classschedule_acad_sched_class_day_idx_and_more'),
        ('assignments', '0002_submission_is_plagiarized_submission_plagiarism_note'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='assignment',
            index=models.Index(fields=['course_class', 'due_date'], name='assign_class_due_idx'),
        ),
        migrations.AddIndex(
            model_name='assignment',
            index=models.Index(fields=['created_by', 'due_date'], name='assign_creator_due_idx'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['assignment', 'graded'], name='sub_assignment_graded_idx'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['student', 'submitted_at'], name='sub_student_submitted_idx'),
        ),
    ]
