# Generated by Django 6.0.4 on 2026-05-07 13:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0002_message_attachment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['receiver', 'is_read', 'sent_at'], name='msg_receiver_read_sent_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['sender', 'sent_at'], name='msg_sender_sent_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['parent', 'sent_at'], name='msg_parent_sent_idx'),
        ),
    ]
