from django.urls import path
from . import views, views_features

urlpatterns = [
    path('', views.dashboard_home, name='dashboard_home'),
    path('command-center/', views.smart_command_center_view, name='smart_command_center'),
    path('planner/', views.planner_view, name='planner'),
    path('launch-center/', views.launch_center_view, name='launch_center'),
    path('integrations/', views.integrations_hub_view, name='integrations_hub'),
    path('departments/', views.departments_view, name='departments'),
    path('classes/', views.classes_view, name='classes'),
    path('users/', views.users_list_view, name='users_list'),
    path('reports/', views.reports_view, name='reports'),
    path('attendance/', views.mark_attendance_view, name='mark_attendance'),
    path('my-attendance/', views.my_attendance_view, name='my_attendance'),
    path('leave-requests/', views.leave_requests_view, name='leave_requests'),
    path('notices/', views.notices_view, name='notices'),
    path('timetable/', views.timetable_view, name='timetable'),
    path('grades/', views.grades_view, name='grades'),
    path('export-reports/', views.export_reports_csv, name='export_reports_csv'),
    path('profile/settings/', views.profile_settings_view, name='profile_settings'),
    path('profile/username-availability/', views.username_availability_view, name='username_availability'),
    path('profile/<int:user_id>/', views.public_profile_view, name='public_profile'),
    path('class/<int:class_id>/', views.classroom_detail_view, name='classroom_detail'),
    # Assignments
    path('assignments/', views.assignments_view, name='assignments'),
    path('assignments/<int:assignment_id>/', views.assignment_detail_view, name='assignment_detail'),
    # Forum
    path('forum/', views.forum_view, name='forum'),
    path('forum/<int:thread_id>/', views.forum_thread_view, name='forum_thread'),
    # Messaging
    path('inbox/', views.inbox_view, name='inbox'),
    path('inbox/sent/', views.sent_messages_view, name='sent_messages'),
    path('inbox/compose/', views.compose_message_view, name='compose_message'),
    path('inbox/<int:message_id>/', views.message_detail_view, name='message_detail'),
    # Calendar, Analytics, Fees, Library, Achievements
    path('calendar/', views.calendar_view, name='calendar'),
    path('event/<int:event_id>/rsvp/', views.toggle_rsvp, name='toggle_rsvp'),
    path('analytics/', views.analytics_view, name='analytics'),
    path('fees/', views.fees_view, name='fees'),
    path('library/', views.library_view, name='library'),
    path('library/request/<int:resource_id>/', views.request_book, name='request_book'),
    path('library/issue/manage/<int:issue_id>/', views.manage_book_issue, name='manage_book_issue'),
    path('achievements/', views.achievements_view, name='achievements'),
    # Polls, Todos, Activity, Help
    path('polls/', views.polls_view, name='polls'),
    path('todos/', views.todos_view, name='todos'),
    path('activity/', views.activity_view, name='activity'),
    path('help/', views.help_view, name='help'),
    # AI Features
    path('ai/chat/', views.ai_chat_view, name='ai_chat'),
    path('ai/chat/send/', views.ai_chat_send, name='ai_chat_send'),
    path('ai/chat/new/', views.ai_chat_new, name='ai_chat_new'),
    path('ai/quiz/', views.ai_quiz_view, name='ai_quiz'),
    path('ai/quiz/generate/', views.ai_quiz_generate, name='ai_quiz_generate'),
    path('ai/summarize/', views.ai_summarize, name='ai_summarize'),
    path('ai/translate/', views.translate_view, name='translate'),
    path('ai/translate/api/', views.translate_api, name='translate_api'),
    path('ai/tts/', views.tts_api, name='tts_api'),
    # Notes
    path('notes/', views.notes_view, name='notes'),

    # ==========================
    # MASSIVE FEATURE EXPANSION
    # ==========================
    path('homework/', views_features.homework_view, name='homework'),
    path('discipline/', views_features.discipline_view, name='discipline'),
    path('guardians/', views_features.guardians_view, name='guardians'),
    path('health/', views_features.health_records_view, name='health_records'),
    path('transport/', views_features.transport_view, name='transport'),
    path('hostel/', views_features.hostel_view, name='hostel'),
    path('inventory/', views_features.inventory_view, name='inventory'),
    path('visitors/', views_features.visitors_view, name='visitors'),
    path('certificates/', views_features.certificates_view, name='certificates'),
    path('complaints/', views_features.complaints_view, name='complaints'),
    path('scholarships/', views_features.scholarships_view, name='scholarships'),
    path('exam-seating/', views_features.exam_seating_view, name='exam_seating'),
    path('recordings/', views_features.recordings_view, name='recordings'),
    path('study-groups/', views_features.study_groups_view, name='study_groups'),
    path('skills/', views_features.skills_view, name='skills'),
    path('feedback/', views_features.feedback_view, name='feedback'),
    path('circulars/', views_features.circulars_view, name='circulars'),
    path('flashcards/', views_features.flashcards_view, name='flashcards'),
    path('diary/', views_features.diary_view, name='diary'),
    path('kanban/', views_features.kanban_view, name='kanban'),
    path('gallery/', views_features.gallery_view, name='gallery'),
    path('mood/', views_features.mood_view, name='mood'),
    path('notifications-prefs/', views_features.notifications_prefs_view, name='notifications_prefs'),
    path('bookmarks/', views_features.bookmarks_view, name='bookmarks'),
    path('pomodoro/', views_features.pomodoro_view, name='pomodoro'),
    path('whiteboard/', views_features.whiteboard_view, name='whiteboard'),
]
